// Generated by CoffeeScript 1.6.3
(function() {
  var FriendsClass, ListController, ajaxGet, app;

  FriendsClass = function() {
    this.list = [];
    return this.demo = function() {
      return this.list = [
        {
          name: "Adam",
          location: "37.47,-122.25"
        }, {
          name: "bob",
          location: "San Francisco"
        }
      ];
    };
  };

  ListController = function($scope, Friends) {
    Friends.demo();
    $scope.friends_list = Friends.list;
    Friends.list.push({
      name: "Miles",
      location: "Daly City"
    });
    return $scope.test = function() {
      return alert(123);
    };
  };

  app = angular.module('pickmeup', [], function($compileProvider) {
    return $compileProvider.urlSanitizationWhitelist(/^\s*(https?|ftp|mailto|file|maps):/);
  });

  ajaxGet = function() {};

  app.filter('escape', function() {
    return window.escape;
  });

  app.service('Friends', FriendsClass);

  app.controller('ListController', ListController);

}).call(this);

/*
//@ sourceMappingURL=controller.map
*/
