// Generated by CoffeeScript 1.6.3
(function() {
  var FriendsClass, ListController, app;

  FriendsClass = function() {
    this.list = [];
    return this.demo = function() {
      return this.list = ["1", "2", "3"];
    };
  };

  ListController = function($scope, Friends) {
    Friends.demo();
    $scope.friends_list = Friends.list;
    return $scope.name_1 = 123;
  };

  app = angular.module('pickmeup', []);

  app.service('Friends', FriendsClass);

  app.controller('ListController', ListController);

}).call(this);

/*
//@ sourceMappingURL=controller.map
*/
