// Generated by CoffeeScript 1.6.3
(function() {
  var FriendsClass, ListController, app;

  FriendsClass = function() {
    this.list = [];
    return this.demo = function() {
      return this.list = ["Adam", "Bob", "Catherine", "Daniel"];
    };
  };

  ListController = function($scope, Friends) {
    Friends.demo();
    $scope.friends_list = Friends.list;
    return Friends.list.push("Miles");
  };

  app = angular.module('pickmeup', []);

  app.service('Friends', FriendsClass);

  app.controller('ListController', ListController);

}).call(this);

/*
//@ sourceMappingURL=controller.map
*/
